export const scheduleData = [
  {
    state: 2,
    dt: '2023년 4월 1일',
    nm: '한마음인테리어',
    tags: ['보증보험가능', '자격증보유', '6개월A/S'],
    review: false,
    isCheck: true,
    imgUrl: require('@/assets/images/pick1.png'),
    thumnailList: [
      require('@/assets/images/hanmaum/1.png'),
      require('@/assets/images/hanmaum/1.png'),
      require('@/assets/images/hanmaum/1.png'),
    ],
  },
  {
    state: 1,
    dt: '2023년 4월 1일',
    nm: '한마음인테리어',
    tags: ['보증보험가능', '6개월A/S'],
    review: false,
    isCheck: false,
    imgUrl: require('@/assets/images/pick-start.png'),
    thumnailList: [
      require('@/assets/images/star/1.png'),
      require('@/assets/images/star/2.png'),
      require('@/assets/images/star/2.png'),
    ],
  },
  {
    state: 1,
    dt: '2023년 4월 1일',
    nm: '코지인테리어',
    tags: ['보증보험가능', '6개월A/S'],
    review: false,
    isCheck: false,
    imgUrl: require('@/assets/images/pick-cozy.png'),
    thumnailList: [
      require('@/assets/images/star/1.png'),
      require('@/assets/images/star/2.png'),
      require('@/assets/images/star/2.png'),
    ],
  },
];

export const scheduleFixedData = [
  {
    state: 2,
    ment: '공사요청하기',
    dt: '2023년 4월 1일',
    nm: '한마음인테리어',
    tags: ['보증보험가능', '자격증보유', '6개월A/S'],
    review: false,
    isCheck: true,
    imgUrl: require('@/assets/images/pick1.png'),
    thumnailList: [
      require('@/assets/images/hanmaum/1.png'),
      require('@/assets/images/hanmaum/1.png'),
      require('@/assets/images/hanmaum/1.png'),
    ],
  },
  {
    state: 2,
    ment: '공사요청하기',
    dt: '2023년 4월 1일',
    nm: '한마음인테리어',
    tags: ['보증보험가능', '6개월A/S'],
    review: false,
    isCheck: false,
    imgUrl: require('@/assets/images/pick-start.png'),
    thumnailList: [
      require('@/assets/images/star/1.png'),
      require('@/assets/images/star/2.png'),
      require('@/assets/images/star/2.png'),
    ],
  },
  {
    state: 2,
    ment: '업체에서 수락대기중 입니다',
    dt: '2023년 4월 1일',
    nm: '한마음인테리어',
    tags: ['보증보험가능', '6개월A/S'],
    review: false,
    isCheck: false,
    imgUrl: require('@/assets/images/pick-start.png'),
    thumnailList: [
      require('@/assets/images/star/1.png'),
      require('@/assets/images/star/2.png'),
      require('@/assets/images/star/2.png'),
    ],
  },
  {
    state: 1,
    dt: '2023년 4월 1일',
    nm: '코지인테리어',
    tags: ['보증보험가능', '6개월A/S'],
    review: false,
    isCheck: false,
    imgUrl: require('@/assets/images/pick-cozy.png'),
    thumnailList: [
      require('@/assets/images/star/1.png'),
      require('@/assets/images/star/2.png'),
      require('@/assets/images/star/2.png'),
    ],
    ment: '방문예정',
  },
  {
    state: 3,
    dt: '2023년 4월 1일',
    nm: '코지인테리어',
    tags: ['보증보험가능', '6개월A/S'],
    review: false,
    isCheck: false,
    imgUrl: require('@/assets/images/pick-cozy.png'),
    thumnailList: [
      require('@/assets/images/star/1.png'),
      require('@/assets/images/star/2.png'),
      require('@/assets/images/star/2.png'),
    ],
    ment: '공사요청불가',
  },
  {
    state: 4,
    dt: '2023년 4월 1일',
    nm: '코지인테리어',
    tags: ['보증보험가능', '6개월A/S'],
    review: false,
    isCheck: false,
    imgUrl: require('@/assets/images/pick-cozy.png'),
    thumnailList: [
      require('@/assets/images/star/1.png'),
      require('@/assets/images/star/2.png'),
      require('@/assets/images/star/2.png'),
    ],
    ment: '공사스케줄을 확인하세요',
  },
];
